### ISSUE TITLE
install through homebrew error

### ISSUE THREAD

**Issue by Cookiezby** [giginet/Toybox#16]
The download url seems wrong when I try to install it.

```
Error:` Failed to download resource "toybox"
Download failed: https://github.com/giginet/Toybox/releases/download/0.2.0/toybox-0.3.0.sierra.bottle.tar.gz
```
I fix it by brew edit and change the root_url to 0.3.0

**Comment by giginet** [comment]
👀 

Thank you for reporting the issue.
I'll check and fix this later.

**Comment by giginet** [comment]
I'm working on. Please try later 🙏 

You can install by manually

```console
$ git clone https://github.com/giginet/Toybox.git
$ make prefix_install PREFIX=`brew --prefix`
```

**Comment by giginet** [comment]
@Cookiezby Sorry about waiting you for such a long time.
I just released Toybox 1.0.1.

Can you try to install this like following?

```console
$ brew tap giginet/toybox https://github.com/giginet/Toybox.git
$ brew install giginet/toybox/toybox
$ toybox version
1.0.1
```

**Comment by Cookiezby** [comment]
Thanks for your update, but it still get some errors.
```
➜  ~ brew tap giginet/toybox https://github.com/giginet/Toybox.git
➜  ~ brew update
remote: Repository not found.
fatal: repository 'https://github.com/giginet/homebrew-toybox/' not found
Error: Fetching /usr/local/Homebrew/Library/Taps/giginet/homebrew-toybox failed!
➜  ~ brew install giginet/toybox/toybox
Warning: giginet/toybox/toybox 0.3.0 is already installed and up-to-date
To reinstall 0.3.0, run `brew reinstall toybox`
```

**Comment by giginet** [comment]
@Cookiezby Thanks for your feedback!

I moved Homebrew formula. Could you try `brew untap giginet/toybox` and retap new one?

**Comment by Cookiezby** [comment]
Hi, I install succeed on my own mac which Xcode version is 9.3, very thanks. 

BTW: Does the v1.0.1  only works on Xcode9.3? Because the install failed on another mac which is using the Xcode9.2. If it only for Xcode9.3, it may be better to have some comment on the README.

**Comment by giginet** [comment]
> BTW: Does the v1.0.1 only works on Xcode9.3? Because the install failed on another mac which is using the Xcode9.2

Toybox migrated to latest Swift (4.1).
So, you can't build on Xcode 9.2.

You are using High Sierra. I provided bottle for that. you can install this without building.
If you are still using (Low) Sierra, we have no bottles.
I'll prepare old version bottles.

**Comment by Cookiezby** [comment]
@giginet Yes the old machine is using Sierra, Thank you very much!

**Comment by giginet** [comment]
I googled, Unfortunately, we have no way to build bottles for old versions on newest OS.
So I haven't support bottle for Sierra.
Please install High Sierra 🙏
